//
// Machine generated by compile-mbh from ./gcp_switch.mbh
//
// protocol-classes: gcp-switch-cs 
//
#include <mb_protocol_class.h>
#include <unistd.h>
static const char
protocol_class_init_data[67] = {
  7, 2, 0, 13, 103, 99, 112, 45, 115, 119, 105, 116, 99, 104, 45, 99, 
  115, 7, 7, 2, 0, 21, 114, 101, 115, 112, 111, 110, 115, 101, 45, 99, 
  111, 110, 110, 101, 99, 116, 45, 109, 97, 99, 115, 6, 7, 7, 2, 0, 
  16, 99, 109, 100, 45, 99, 111, 110, 110, 101, 99, 116, 45, 109, 97, 99, 
  115, 6, 6, 
};
static mb_protocol_class_init _init_(protocol_class_init_data, sizeof(protocol_class_init_data));
