CC=gcc 
CFLAGS=-Wall
main: read_binary_complex read_binary_float read_short_complex convert_short_to_complex

clean:
	rm -f read_binary_complex read_binary_float read_short_complex convert_short_to_complex
